services:

  frontend:
    build: myshop_front
    env_file:
      - .env
    volumes:
      - $FRONTEND_PATH:/usr/app/staticfiles
    command: npm run build

  web-static:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/www/
      - $FRONTEND_PATH:/www/staticfiles
    command: python manage.py collectstatic --noinput
    depends_on:
      - frontend

  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/www/
      - $MEDIA_PATH:/www/media
      - $FRONTEND_PATH:/www/staticfiles
    ports:
      - "8000:8000"
    network_mode: host 
    depends_on:
      - web-static

  
  #db:
  #  image: postgres:14.0-alpine
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data/
  #  environment:
  #    - .env
  #    - POSTGRES_USER=$POSTGRES_USER
  #    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  #    - POSTGRES_DB=$POSTGRES_DB

volumes:
  #postgres_data:
  frontend:
  media: