# Generated by Django 5.0.3 on 2024-03-25 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('first_attempt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Первая попытка')),
                ('attempt_count', models.SmallIntegerField(verbose_name='Кол-во попыток')),
                ('blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Бан',
                'verbose_name_plural': 'Баны',
            },
        ),
    ]
