# Generated by Django 5.0.3 on 2024-03-25 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=500, verbose_name='Ключ сессии')),
                ('first_request', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Первое обращение')),
                ('last_request', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обращение')),
                ('ip', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.CharField(max_length=1000, verbose_name='User agent')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
    ]
