# Generated by Django 5.0.3 on 2024-03-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_metrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_history', to='guard.metrica')),
            ],
        ),
    ]
