# Generated by Django 5.0.3 on 2024-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0004_responseerrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseerrors',
            name='request',
            field=models.CharField(default=0, max_length=1000, verbose_name='Запрос'),
            preserve_default=False,
        ),
    ]
