# Generated by Django 5.0 on 2024-03-05 08:58

import django.db.models.deletion
import django.utils.timezone
import main.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('is_read_pd', models.BooleanField(default=False, verbose_name='Соглашение прочтено')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('login_fail_counter', models.SmallIntegerField(default=0, verbose_name='Счетчик неудачных входов')),
                ('ban_status', models.BooleanField(default=False, verbose_name='Бан или нет')),
                ('ban_time', models.DateTimeField(blank=True, null=True, verbose_name='Время бана')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название каталога')),
                ('code_1c', models.PositiveIntegerField(blank=True, null=True, verbose_name='Код каталога из 1С')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/catalog_images', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывается')),
                ('slug', models.SlugField(max_length=200)),
                ('order', models.IntegerField(default=1, verbose_name='Порядок')),
                ('icon', models.CharField(blank=True, max_length=250, null=True, verbose_name='Код иконки')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Наименование статуса заказа')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CustomerBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время бана')),
                ('ban_reazon', models.CharField(max_length=500, verbose_name='Причина бана')),
                ('ban_before', models.DateTimeField(default=main.models.CustomerBan.ban_delta, verbose_name='Бан до:')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бан пользователя',
                'verbose_name_plural': 'Баны пользователей',
            },
        ),
        migrations.CreateModel(
            name='CustomerLoginFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_fail_last_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последннего неудачного входа')),
                ('login_fail_counter', models.SmallIntegerField(default=1, verbose_name='Счетчик неудачных входов')),
                ('login_fail_total_counter', models.PositiveIntegerField(default=1, verbose_name='Счетчик всех неудачных входов')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_failed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счетчик неудачных входов пользователя',
                'verbose_name_plural': 'Счетчики неудачных входов пользователей',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время заказа')),
                ('order_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время изменения заказа')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
                ('order_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.orderstatus')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, default='Нет описания', null=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Показывается')),
                ('slug', models.SlugField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Рейтинг')),
                ('show_count', models.BigIntegerField(default=0, verbose_name='Кол-во показов')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Размер скидки')),
                ('code_1c', models.PositiveIntegerField(blank=True, null=True, verbose_name='Код из 1С')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=9, verbose_name='Количество')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.catalog', verbose_name='В каталоге')),
                ('tags', models.ManyToManyField(blank=True, to='main.tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name', '-create_date', 'show_count'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main.product', verbose_name='Лайкнутые товары'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=100, verbose_name='Alt изображения')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default='1.0', max_digits=6, verbose_name='Количество в корзине')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зафиксированая цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_carts', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default='1.0', max_digits=6, verbose_name='Количество в корзине')),
                ('fixed_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Зафиксированая цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_order', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Weight')),
                ('width', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Ширина см')),
                ('height', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Высота см')),
                ('length', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Длинна см')),
                ('image', models.ImageField(upload_to='media/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.product')),
            ],
            options={
                'verbose_name': 'Product property',
                'verbose_name_plural': 'Product properties',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Рейтинг')),
                ('counter', models.IntegerField(default=0, verbose_name='Кол-во оценок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_rating', to='main.product')),
            ],
            options={
                'verbose_name': 'Рейтинг товара',
                'verbose_name_plural': 'Рейтинги товаров',
            },
        ),
    ]
