# Generated by Django 5.0 on 2024-01-01 16:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название каталога')),
                ('code_1c', models.PositiveIntegerField(verbose_name='Код каталога из 1С')),
                ('image', models.ImageField(upload_to='media/catalog_images', verbose_name='Изображение')),
                ('is_active', models.BooleanField(verbose_name='Показывается')),
                ('slug', models.SlugField(max_length=200)),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('icon', models.CharField(max_length=250, verbose_name='Код иконки')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_read_pd',
            field=models.BooleanField(default=False, verbose_name='Соглашение прочтено'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('code_1c', models.PositiveIntegerField(verbose_name='Код из 1С')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена')),
                ('available', models.BooleanField(verbose_name='Показывается')),
                ('slug', models.SlugField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Количество')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Размер скидки')),
                ('show_count', models.BigIntegerField(verbose_name='Кол-во показов')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.catalog', verbose_name='В каталоге')),
                ('tags', models.ManyToManyField(to='main.tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Вес')),
                ('width', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Высота')),
                ('length', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Длинна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='likes',
            field=models.ManyToManyField(to='main.product', verbose_name='Лайкнутые товары'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=100, verbose_name='Alt изображения')),
                ('image', models.ImageField(upload_to='media/product_images', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
