# Generated by Django 5.0 on 2024-01-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_catalog_tag_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
