# Generated by Django 5.0 on 2024-01-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='code_1c',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код каталога из 1С'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='icon',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Код иконки'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/catalog_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывается'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Показывается'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_1c',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код из 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_count',
            field=models.BigIntegerField(default=0, verbose_name='Кол-во показов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='main.tag', verbose_name='Тэг'),
        ),
    ]
