# Generated by Django 5.0 on 2023-12-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('description', models.TextField()),
                ('code_1c', models.IntegerField(verbose_name='Код из 1С')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='id_1c',
        ),
        migrations.AddField(
            model_name='catalog',
            name='code_1c',
            field=models.IntegerField(default=0, verbose_name='Код каталога из 1С'),
            preserve_default=False,
        ),
    ]
