# Generated by Django 5.0 on 2023-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_remove_catalog_id_1c_catalog_code_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='code_1c',
            field=models.PositiveIntegerField(verbose_name='Код каталога из 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_1c',
            field=models.PositiveIntegerField(verbose_name='Код из 1С'),
        ),
    ]
