# Generated by Django 5.0 on 2024-03-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_customer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='customer',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main.product', verbose_name='Лайкнутые товары'),
        ),
    ]
