# Generated by Django 5.0 on 2024-01-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_catalog_code_1c_alter_catalog_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag', verbose_name='Тэг'),
        ),
    ]
