# Generated by Django 5.0 on 2024-01-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_colorproperty_productproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
