# Generated by Django 5.0.3 on 2024-03-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='personal_discount',
            field=models.SmallIntegerField(default=0, verbose_name='Персональная скидка'),
        ),
    ]
