# Generated by Django 5.0 on 2023-12-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0008_productpropertycontent_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productpropertycontent',
            index=models.Index(fields=['content_type', 'object_id'], name='main_produc_content_8d4999_idx'),
        ),
    ]
