# Generated by Django 5.0 on 2024-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productproperty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Высота см'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productproperty',
            name='length',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Длинна см'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productproperty',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productproperty',
            name='width',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Ширина см'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.DeleteModel(
            name='ColorProperty',
        ),
    ]
