# Generated by Django 5.0 on 2023-12-31 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productpropertycontent_main_produc_content_8d4999_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertycontent',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
    ]
