# Generated by Django 5.0 on 2024-01-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productproperty_color_productproperty_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9, verbose_name='Количество'),
        ),
    ]
