# Generated by Django 5.0.3 on 2024-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_productproperty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для свойства'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Высота м'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='length',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Длинна м'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Ширина м'),
        ),
    ]
