# Generated by Django 5.0 on 2024-01-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productproperty_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Размер скидки'),
        ),
    ]
