# Generated by Django 5.0 on 2024-01-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_product_discount_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code_1c',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='code_1c',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код из 1С'),
        ),
    ]
