# Generated by Django 5.0 on 2023-12-31 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0011_color_content_type_color_object_id_color_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='color',
            name='id',
        ),
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.RemoveField(
            model_name='color',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='productprop_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.productprop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='productprop_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.productprop'),
            preserve_default=False,
        ),
    ]
