# Generated by Django 5.0 on 2024-01-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_productproperty_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='product',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
    ]
