# Generated by Django 5.0.3 on 2024-03-26 03:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_cart_customer_customer_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отзыва')),
                ('positive', models.TextField(verbose_name='Положительные моменты')),
                ('negative', models.TextField(verbose_name='Отрицательные моменты')),
                ('summary', models.TextField(verbose_name='Общий отзыв')),
                ('rating', models.SmallIntegerField(verbose_name='Рейтинг')),
                ('is_show', models.BooleanField(verbose_name='Отображается')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feedbacks', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
