# Generated by Django 5.0.3 on 2024-03-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Отображается'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='negative',
            field=models.TextField(blank=True, null=True, verbose_name='Отрицательные моменты'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='positive',
            field=models.TextField(blank=True, null=True, verbose_name='Положительные моменты'),
        ),
    ]
