# Generated by Django 5.0 on 2024-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_customer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='code_1c',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='code_1c',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код из 1С'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Размер скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9, verbose_name='Количество'),
        ),
    ]
