# Generated by Django 5.0.3 on 2024-03-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_feedback_is_show_alter_feedback_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Вес кг'),
        ),
    ]
