# Generated by Django 5.0 on 2024-03-27 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_productproperty_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Тескт вопроса')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('is_show', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_qusetions', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вопрос к товару',
                'verbose_name_plural': 'Вопросы к тоаварам',
            },
        ),
    ]
