# Generated by Django 5.0 on 2024-02-14 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_product_description_cart_productincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Рейтинг')),
                ('counter', models.IntegerField(default=0, verbose_name='Кол-во оценок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_rating', to='main.product')),
            ],
            options={
                'verbose_name': 'Рейтинг товара',
                'verbose_name_plural': 'Рейтинги товаров',
            },
        ),
    ]
