# Generated by Django 5.0 on 2024-02-18 12:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ban_status',
            field=models.BooleanField(default=False, verbose_name='Бан или нет'),
        ),
        migrations.AddField(
            model_name='customer',
            name='login_fail_counter',
            field=models.SmallIntegerField(default=0, verbose_name='Счетчик неудачных входов'),
        ),
        migrations.CreateModel(
            name='CustomerBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_datetime', models.DateTimeField(default=datetime.datetime(2024, 2, 18, 12, 56, 4, 219620, tzinfo=datetime.timezone.utc), verbose_name='Время бана')),
                ('ban_reazon', models.CharField(max_length=500, verbose_name='Причина бана')),
                ('ban_before', models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 56, 4, 219670, tzinfo=datetime.timezone.utc), verbose_name='Бан до:')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бан пользователя',
                'verbose_name_plural': 'Баны пользователей',
            },
        ),
        migrations.CreateModel(
            name='CustomerLoginFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_fail_last_time', models.DateTimeField(default=datetime.datetime(2024, 2, 18, 12, 56, 4, 220103, tzinfo=datetime.timezone.utc), verbose_name='Время последннего неудачного входа')),
                ('login_fail_counter', models.SmallIntegerField(default=1, verbose_name='Счетчик неудачных входов')),
                ('login_fail_total_counter', models.PositiveIntegerField(default=1, verbose_name='Счетчик всех неудачных входов')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_failed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счетчик неудачных входов пользователя',
                'verbose_name_plural': 'Счетчики неудачных входов пользователей',
            },
        ),
    ]
