# Generated by Django 5.0 on 2024-03-27 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_text_productquestion_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_questions', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
