# Generated by Django 5.0.3 on 2024-03-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_productquestion_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='expiration_date',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Срок годности. Месяцев'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='material',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Материал\\состав'),
        ),
    ]
