# Generated by Django 5.0 on 2024-02-18 12:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_customer_ban_status_customer_login_fail_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerban',
            name='ban_before',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 57, 4, 449106, tzinfo=datetime.timezone.utc), verbose_name='Бан до:'),
        ),
        migrations.AlterField(
            model_name='customerban',
            name='ban_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 12, 57, 4, 449061, tzinfo=datetime.timezone.utc), verbose_name='Время бана'),
        ),
        migrations.AlterField(
            model_name='customerloginfail',
            name='login_fail_last_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последннего неудачного входа'),
        ),
    ]
