# Generated by Django 5.0 on 2024-03-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_productproperty_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='production_origin',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='production_origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна производитель'),
        ),
    ]
