# Generated by Django 5.0 on 2024-03-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_product_production_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='image',
        ),
    ]
