# Generated by Django 5.0 on 2024-02-18 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_customerban_ban_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerban',
            name='ban_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время бана'),
        ),
    ]
