# Generated by Django 5.0 on 2024-03-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_productproperty_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Высота м.'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='length',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Длинна м.'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Вес кг.'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Ширина м.'),
        ),
    ]
