# Generated by Django 5.0 on 2024-03-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_productproperty_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='description',
            field=models.TextField(default='', verbose_name='Описание для свойства'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='expiration_date',
            field=models.SmallIntegerField(default=0, verbose_name='Срок годности. Месяцев'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Высота м.'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='length',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Длинна м.'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='material',
            field=models.CharField(default='', max_length=250, verbose_name='Материал\\состав'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='production_origin',
            field=models.CharField(default='', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Вес кг.'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='width',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Ширина м.'),
        ),
    ]
