# Generated by Django 5.0 on 2024-03-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_productproperty_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание для свойства'),
        ),
    ]
