# Generated by Django 5.0 on 2024-03-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_productproperty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='material',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Материал\\состав'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='production_origin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Страна производитель'),
        ),
    ]
