# Generated by Django 5.0.3 on 2024-04-01 06:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_productproperty_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пункт выдачи')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
            },
        ),
    ]
