# Generated by Django 5.0 on 2024-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Зафиксированая цена'),
        ),
    ]
