# Generated by Django 5.0.3 on 2024-04-01 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_pickpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pickpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickpoints', to='main.pickpoint'),
        ),
    ]
