# Generated by Django 5.0.4 on 2024-04-25 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_product_code_1c'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пункт главного меню')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'Элемент главного меню',
                'verbose_name_plural': 'Элементы главного меню',
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пункт подменю')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка на страницу')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='main.mainmenuitem')),
            ],
            options={
                'verbose_name': 'Элемент подменю',
                'verbose_name_plural': 'Элементы подменю',
            },
        ),
    ]
