# Generated by Django 5.0 on 2024-02-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_customer_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_staff',
        ),
    ]
