# Generated by Django 5.0.3 on 2024-05-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_product_first_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Онлайн цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Розничная цена'),
        ),
    ]
