# Generated by Django 5.0 on 2024-02-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_stuff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
    ]
