# Generated by Django 5.0.3 on 2024-05-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_product_online_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.catalog', verbose_name='В каталоге'),
        ),
    ]
