# Generated by Django 5.0 on 2024-02-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_customer_is_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
