# Generated by Django 5.0.3 on 2024-05-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_product_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Главный слайдер')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='sliders')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок слайда')),
                ('text', models.CharField(max_length=200, verbose_name='Текст слайда')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
