# Generated by Django 5.0.4 on 2024-05-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_mainslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Показ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Закуп. цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Розн. цена'),
        ),
    ]
