# Generated by Django 5.0 on 2024-02-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_customer_managers_customer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
