# Generated by Django 5.0 on 2024-02-29 10:46

import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_customer_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', main.models.CustomerManager()),
            ],
        ),
    ]
