# Generated by Django 5.0.4 on 2024-05-16 12:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_simplepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepage',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
