# Generated by Django 5.0.4 on 2024-05-21 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linked_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linked_product', to='main.product', verbose_name='Связан с товаром'),
        ),
    ]
