# Generated by Django 5.0.4 on 2024-05-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_product_linked_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='linked_products',
        ),
        migrations.AddField(
            model_name='product',
            name='linked_products',
            field=models.ManyToManyField(to='main.product', verbose_name='Связанные товары'),
        ),
    ]
